spring:
  application:
    name: spring-ai
  ai:
    openai:
      # 访问模型地址
      base-url: https://api.deepseek.com
      # 访问模型的秘钥，也就是身份证明
      api-key: ${Deepseek_Key}
      chat:
        options:
          # 模型名称
          model: deepseek-v4-flash
      embedding:
        options:
          model: text-embedding-v3 # embedding模型的名称
          dimensions: 1024 # 生成的向量维数
        vectorstore:
          elasticsearch:
            index-name: spring-ai-docs
            dimensions: 1024
            initialize-schema: true # 自动创建索引

        elasticsearch:
          uris: http://192.168.74.100:9200
logging:
  level:
    # 指定SimpleLoggerAdvisor日志输出级别
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
